# AUTOGENERATED FROM 'app/queries/get_user_by_name.edgeql' WITH:
#     $ edgedb-py --dsn=edgedb://clgbnxthc000s9ho4en8sdf5n:yjI0yQ87sRlW6fPFy3HGstkR@64.227.146.174:9000/clgbnxthc000t9ho41lc6afnf --tls-security insecure


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import typing
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserByNameResult(NoPydanticValidation):
    id: uuid.UUID
    name: typing.Optional[str]
    dob: typing.Optional[datetime.date]


async def get_user_by_name(
    executor: edgedb.AsyncIOExecutor,
    *,
    name: str,
) -> list[GetUserByNameResult]:
    return await executor.query(
        """\
        select User {name, dob}
        filter User.name = <str>$name\
        """,
        name=name,
    )
